# AUTOR: RIQUISIMO

# PEDIRLE AL USUARIO QUE DIGA CUALQUIER TEXTO REAL Y HACER LOS CALCULOS A) Y B)
textoReal = input("INGRESA UN TEXTO: ")

# CALCULAR CUANTO TARDA EN DECIR ESE TEXTO
palabrasSeparadas = textoReal.split(" ")

# CONSIDERANDO QUE UN HUMANO PROMEDIO HABLA 2 PALABRAS POR SEGUNDO
tiempo = len(palabrasSeparadas) * 2

numPalabras = len(palabrasSeparadas)

# ENVIAR UN MENSAJE SI TARDA MAS DE UN MINUTO EN DECIR EL TEXTO
if tiempo > 60:
    print("HEY TRANQUILO, TAMPOCO TE PEDI UN TESTAMENTO")

# IMPRIMIR EL RESULTADO
print(f"TU TEXTO TIENE: {numPalabras} PALABRAS")
print(f"TE TARDARIAS: {tiempo} SEGUNDOS EN DECIR ESE TEXTO")

# CALCULAR CUANTO TARDARIA DALTO (CONSIDERANDO QUE HABLA 30% MAS RAPIDO)
tiempoDalto = round(tiempo - (tiempo/100) * 30, 2) # USAR ROUND PARA EVITAR DECIMALES EXTENSON EN ALGUN CASO
# FORMA 2: tiempoDalto = tiempo / 100 * 70
# FORMA 3: tiempoDalto = tiempo * 0.7
print(f"DALTO TARDARIA: {tiempoDalto} SEGUNDOS EN DECIR EL MISMO TEXTO")