# AUTOR: RIQUISIMO
"""
DENTRO DE open() AL ENVIAR EL PARAMETRO "w" WRITE ESTAMOS PIDIENDO PERMISOS PARA ESCRITURA
CON ESTE PARAMETRO SI NO ENCUENTRA EL ARCHIVO LO CREA
ESTE PARAMETRO SIEMPRE SOBREESCRIBE EL ARCHIVO, ELIMINA LO QUE TIENE Y ESCRIBE ALGO NUEVO
"""

with open("src/14_archivos/data.txt", "w",encoding="UTF-8") as archivo:
    # SOBREESCRIBIENDO EL ARCHIVO
    # archivo.write("HOLA")

    # ESCRIBIR 2 LINEAS (SE ACUMULAN)
    archivo.writelines(["HOLA\n","QUE\n","TAL\n"])
    archivo.writelines(["HOLA\n","QUE\n","TAL\n"])