# AUTOR: RIQUISIMO

"""
EL CICLO WHILE A DIFERENCIA DEL FOR SE EJECUTA NO SOLO CUANDO HAY UN ITERABLE SI NO QUE
SE EJECUTA SIEMPRE Y CUANDO SE CUMPLA UNA CONDICION QUE NOSOTROS LE DEMOS
ESTE TIPO DE CICLO SE PUEDEN TORNAR INFINITOS YA QUE NOSOTROS ASIGNAMOS LA CONDICION

ESTRUCTURA:
while condicion:
    acciones
"""

# EJEMPLO 1
# POR LO GENERAL SE NECESITA DE UNA VARIABLE PARA CONTROLAR LAS ITERACIONES
# MIENTRAS LA CONDICION SEA TRUE ENTRA AL CICLO
contador = 1
while contador <= 5:
    print(f"VUELTA #{contador}")
    contador+=1
else:
    print("CICLO TERMINADO") # TAMBIEN FUNCIONA CON ELSE